export const site = {
  brand: 'Transistor&CIE',
  brandAliases: [
    'Transistor et CIE',
    'Transistor & CIE',
    'Transistor CIE',
    'Transistor-cie',
    'Transistor et compagnie',
    'Transistor & compagnie',
    'Transistor compagnie',
    'Transistor&compagnie',
  ],
  heroTitle: 'La tech au quotidien, simplifiée',
  heroSubtitle: 'Performance & Responsabilité',
  remotePromise: '100% digital, partout en France — Devis gratuit',
  websiteUrl: 'https://www.transistor-cie.fr',
  contactEmail: 'contact@transistor-cie.fr',
  phoneDisplay: '09 72 22 96 18',
  phoneHref: '+33972229618',
  whatsappUrl: 'https://wa.me/33972229618',
  instagramHandle: '@Transistor_CIE',
  instagramUrl: 'https://www.instagram.com/Transistor_CIE/',
}
